spring:
  application:
    name: BooksBackend
  docker:
    compose:
      file: dev-compose.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_JDBC_URL}
  jpa:
    hibernate:
      ddl-auto: update
  #    show-sql: true
  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
        endpoint: ${S3_ENDPOINT}
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ${S3_REGION}
  cache:
    caffeine:
      spec: maximumSize=1000
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 16MB # на всякий

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

springdoc:
  paths-to-match: /api/**
  swagger-ui:
    path: /docs/
  api-docs:
    path: /docs/v3

server:
  port: ${SERVER_PORT:8080}
  servlet:
    session:
      cookie:
        max-age: 86400
        same-site: none
        secure: true
        http-only: off